### ISSUE TITLE
log.py filename crash

### ISSUE THREAD

**Issue by Syras5** [DiamondLightSource/diffcalc-core#20]
* diffcalc version: 0.3.0
* Python version: 3.9.2
* Operating System: Windows 10 Enterprise
[log error.txt](https://github.com/DiamondLightSource/diffcalc-core/files/6815916/log.error.txt)

### Description
I was trying to run the sixcircle.py example after pip-installing diffcalc core.

### What I Did
The script failed when trying to run "from diffcalc.hkl.calc import HklCalculation", because the file given in log.py does not exist.
I fixed it by giving it a path to an existing file, and now it works fine. 

It would be nice if could run diffcalc-core without editing the source files in the future.
Cheers!
```
Traceback:
  File "C:\Unsorted Stuff\Work Files\Blender tests\Prototype\Script tests\prototype12.blend\six_circle.py", line 12, in <module>
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\diffcalc\hkl\calc.py", line 20, in <module>
    from diffcalc.log import logging
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\diffcalc\log.py", line 5, in <module>
    logging.basicConfig(
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\logging\__init__.py", line 1999, in basicConfig
    h = FileHandler(filename, mode,
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\logging\__init__.py", line 1142, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\logging\__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\tmp\\diffcalc_axw86756.log'
Error: Python script failed, check the message in the system console
```

**Comment by Syras5** [comment]
After getting the latest version, diffcalc-core works fine in an anaconda environment.  Unfortunately, the internal python version in Blender does not have the 'pwd' module, so it still causes diffcalc-core to crash. 

diffcalc-core seems to be as good as it can get, but I will need to edit the source files one way or another to make it work in Blender.

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\axw86756\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i16sim\DiffcalcEmulator.py", line 27, in <module>
    from diffcalc.hkl.calc import HklCalculation
  File "C:\Users\axw86756\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\diffcalc\hkl\calc.py", line 20, in <module>
    from diffcalc.log import logging
  File "C:\Users\axw86756\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\diffcalc\log.py", line 8, in <module>
    filename="/tmp/diffcalc_%s.log" % getpass.getuser(),
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\getpass.py", line 168, in getuser
    import pwd
ModuleNotFoundError: No module named 'pwd'
