### ISSUE TITLE
Formating of position object in diffcalc.hkl.calc.py '_verify_pos_map_to_hkl' exception

### ISSUE THREAD

**Issue by AurysSilinga** [DiamondLightSource/diffcalc-core#23]
* diffcalc version: 0.30
* Python version: 3.9.2, internal Blender verion
* Operating System: Windows 10 Enterprise

### Description

I tried to calculate a move to a hkl position after manually setting a UB matrix I copied from a nexus file of a real experiment. The exception output string did not have the calculated position, but a pointer to the position object instead. I assume it was supposed to be Eulerian angles.

Also, would anyone have an idea what can cause this error in the first place?
edit: This can happen if the real space lattice does not match the UB matrix

### What I Did

```
>>> pos(hkl, [0.2,-0.2,4])
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Users\axw86756\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i16sim\DiffcalcEmulator.py", line 365, in pos
    pos, virtual_angles = self.pos_from_hkl(val)
  File "C:\Users\axw86756\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i16sim\DiffcalcEmulator.py", line 256, in pos_from_hkl
    for pos, virtual_angles in self.hklcalc.get_position(hkl[0], hkl[1], hkl[2], self.wl):
  File "C:\Users\axw86756\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i16sim\diffcalc\hkl\calc.py", line 200, in get_position
    self._verify_pos_map_to_hkl(h, k, l, wavelength, pos)
  File "C:\Users\axw86756\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i16sim\diffcalc\hkl\calc.py", line 1756, in _verify_pos_map_to_hkl
    raise DiffcalcException(s)
i16sim.diffcalc.util.DiffcalcException: 

***********************************************************************************************************************************************
* ERROR: The angles calculated for hkl=(0.200000,-0.200000,4.000000) were <i16sim.diffcalc.hkl.geometry.Position object at 0x0000028E4793BD90>.
* Converting these angles back to hkl resulted in hkl=(0.203564,-0.203564,4.071290)
***********************************************************************************************************************************************
```

**Comment by isikhar** [comment]
Position object string representation added in [3c0fe65](https://github.com/DiamondLightSource/diffcalc-core/commit/3c0fe652c786828f74631f50930dea400d26b0f3).
The calculation works on main branch:
```python
>>> ubcalc.UB
array([[ 1.25663706e+00, -2.02082652e-16, -2.02082652e-16],
       [ 0.00000000e+00,  1.25663706e+00, -7.69468277e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.25663706e+00]])
>>> wl = 1.0
>>> cons = Constraints({"psi": 0, "mu": 0, "nu": 0})
>>> hklcalc = HklCalculation(ubcalc, cons)
>>> hkl1 = (0.2, -0.2, 4)
>>> all_pos = hklcalc.get_position(*hkl1, wl)
>>> for pos, virt in all_pos:
...   pprint(pos.asdict)
...   pprint(virt)
...   print()
... 
{'chi': 87.13759477388825,
 'delta': 47.28126043374469,
 'eta': 26.49947005949833,
 'mu': 0.0,
 'nu': 0.0,
 'phi': -90.0}
{'alpha': -63.50052994050167,
 'beta': 69.21820962575364,
 'betain': 26.463834944196513,
 'betaout': 20.75466392846533,
 'naz': 90.00000000000001,
 'psi': -5.683594414821843e-15,
 'qaz': 90.0,
 'tau': 87.14116015737402,
 'theta': 23.640630216872346,
 'ttheta': 47.28126043374469}

{'chi': -87.13759477388825,
 'delta': 47.28126043374469,
 'eta': -153.50052994050168,
 'mu': 0.0,
 'nu': 0.0,
 'phi': 90.0}
{'alpha': -63.50052994050167,
 'beta': 69.21820962575364,
 'betain': 26.463834944196513,
 'betaout': 20.75466392846532,
 'naz': 90.0,
 'psi': 0.0,
 'qaz': 90.0,
 'tau': 87.14116015737402,
 'theta': 23.640630216872346,
 'ttheta': 47.28126043374469}

{'chi': 92.86240522611176,
 'delta': -47.28126043374469,
 'eta': 153.50052994050168,
 'mu': 0.0,
 'nu': 0.0,
 'phi': 90.0}
{'alpha': -63.50052994050167,
 'beta': 69.21820962575364,
 'betain': 26.463834944196513,
 'betaout': 20.75466392846532,
 'naz': -90.00000000000001,
 'psi': 5.683594414821843e-15,
 'qaz': -90.0,
 'tau': 87.14116015737402,
 'theta': 23.640630216872346,
 'ttheta': 47.28126043374469}

{'chi': -92.86240522611176,
 'delta': -47.28126043374469,
 'eta': -26.49947005949833,
 'mu': 0.0,
 'nu': 0.0,
 'phi': -90.0}
{'alpha': -63.50052994050167,
 'beta': 69.21820962575364,
 'betain': 26.463834944196513,
 'betaout': 20.75466392846532,
 'naz': -90.0,
 'psi': 0.0,
 'qaz': -90.0,
 'tau': 87.14116015737402,
 'theta': 23.640630216872346,
 'ttheta': 47.28126043374469}

>>> 

```
